### ISSUE TITLE
SSL certificate: self signed certificate in certificate chainbool

### ISSUE THREAD

**Issue by xoco70** [jordanandree/jazz-api#1]
Hi, 

Tx for your API, it is very nice.
Had this issue, I resolved it adding : 
    $opts[CURLOPT_SSL_VERIFYPEER] =  false;
L199.
I don't know very well git, but when tried to push, it gave me a 403 Error. So I let you upload it !
Tx

**Comment by jordanandree** [comment]
Sorry for super late response. Are you still getting this error? 

I can dig into it further, but you might have already found a fix.
